import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { PAGES, generate } from '../../bin/build-pages.mjs';

/**
 * The landing pages, /help and /changelog are rendered from markdown by
 * bin/build-pages.mjs at build / dev time (vite plugin `generated-pages`);
 * the outputs are not committed, so nothing can go stale -- what is checked
 * here is that the generator turns the real sources into pages of the right
 * shape. The shell contract (canonical/hreflang/JSON-LD/sitemap) is covered
 * by landing-pages.test.ts, which validates the same in-memory render.
 */
const ROOT = resolve(__dirname, '../..');

describe('generated markdown pages', () => {
  it('renders every page for every locale it has a source for', () => {
    const outputs = generate({ outDir: null });
    const expected = PAGES.reduce((n: number, p: { sources: object }) => n + Object.keys(p.sources).length, 0);
    expect(outputs.length).toBe(expected);
    for (const o of outputs) {
      expect(o.html.startsWith('<!doctype html>\n<!-- GENERATED by bin/build-pages.mjs')).toBe(true);
      expect(o.html).toContain(`<link rel="canonical" href="https://edit.chaxus.com${o.route}" />`);
      // Two shapes out of one shell: a landing page leads with a call to
      // action and no "source" footnote, a documentation page is prose with
      // code and tables (.doc).
      expect(o.html).toContain(o.kind === 'landing' ? 'class="wrap"' : 'class="wrap doc"');
      // Exactly one h1: the shell's. Sources' own top heading is stripped.
      expect(o.html.match(/<h1[\s>]/g)?.length).toBe(1);
    }
  });

  it('help pages carry FAQPage JSON-LD built from their question headings', () => {
    const help = generate({ outDir: null }).find((o: { route: string }) => o.route === '/help')!;
    const ld = JSON.parse(help.html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)![1]);
    const faq = ld['@graph'].find((n: any) => n['@type'] === 'FAQPage');
    expect(faq.mainEntity.length).toBeGreaterThan(10);
    expect(faq.mainEntity[0].name).toMatch(/\?$/);
    expect(faq.mainEntity[0].acceptedAnswer.text.length).toBeGreaterThan(20);
  });

  it('the changelog page renders the same CHANGELOG.md the release notes come from', () => {
    const md = readFileSync(resolve(ROOT, 'CHANGELOG.md'), 'utf8');
    const firstBullet = md
      .split('\n')
      .find((l) => l.startsWith('- '))!
      .slice(2);
    // Compare on plain words: the page escapes quotes and drops inline markup.
    const words = firstBullet
      .replace(/[`*"'()]/g, '')
      .split(/\s+/)
      .slice(0, 5)
      .join(' ');
    const page = generate({ outDir: null }).find((o: { route: string }) => o.route === '/changelog')!.html;
    expect(page.replace(/<[^>]+>/g, '').replace(/&quot;|&#39;/g, '')).toContain(words);
  });
});
